[BID-40] Form de creación de subastas: Ficha técnica
Bid4Wheels/Bid4WheelsFront pull request #27
Opened 2023-09-05 00:24 UTC by valendc15

Creado Form de creacion de subastas + palette

2023-09-06 14:37 UTC, agustinVon requested changes

2023-09-06 14:37 UTC, agustinVon commented on src/features/newAuction/CreateAuction.js
> +                            }}
Pone gap:30px a este box

2023-09-06 14:37 UTC, agustinVon commented on src/features/newAuction/CreateAuction.js
> +                                    marginTop: '69px',
vola estos margenes top

2023-09-06 14:37 UTC, agustinVon commented on src/features/newAuction/CreateAuction.js
> +                                    marginTop: '69px',
Y fijate que falta el nombre por arrriba del input

2023-09-06 14:37 UTC, agustinVon commented on src/features/newAuction/CreateAuction.js
> +                                    marginTop: '69px',
hay una prop de mui para eso

2023-09-06 14:37 UTC, agustinVon commented on src/features/newAuction/CreateAuction.js
> +                        marginTop: '60px',
bajate este margin a 50px

2023-09-06 23:58 UTC, agustinVon requested changes

2023-09-06 23:58 UTC, agustinVon commented on src/App.js
> +                    <Route path="/auction/new" Component={CreateAuction} />
La route tiene que ser /newAuction

2023-09-07 01:57 UTC, flor-resoagli requested changes

2023-09-07 01:57 UTC, flor-resoagli commented on src/features/newAuction/CreateAuction.js
> +const brandOptions = ['Brand 1', 'Brand 2', 'Brand 3'];
para las opciones de brand, color, fuel type, car doors y gear shift type la idea es que uses el file de constants que armo ivan (ya esta mergeado en dev) asi es mas flexible/escalable para cambios mas adelante

2023-09-07 15:31 UTC, agustinVon requested changes

2023-09-07 15:31 UTC, agustinVon commented on src/features/auction/Auction.js
> -import { ImageCarousel } from './ImageCarousel';
Se rompio algo en el merge. Podes revertir y mergear de nuevo?

2023-09-07 15:34 UTC, agustinVon commented on src/features/auction/Auction.js
> -import { ImageCarousel } from './ImageCarousel';
Fijate de no borrar los cambios en develop

2023-09-07 22:01 UTC, agustinVon approved these changes

2023-09-07 22:02 UTC, flor-resoagli approved these changes

2023-09-07 22:02 UTC, merged