[BID-43] Componente de filtrado de subastas
Bid4Wheels/Bid4WheelsFront pull request #29
Opened 2023-09-05 22:52 UTC by ChinoCoder

Necesita fix:
Color de underline de customTagsAutocomplete (no econtré cómo se llama para modificarlo)
La lista de posibles Tags es una auxiliar de momento

2023-09-06 14:18 UTC, agustinVon requested changes

2023-09-06 14:18 UTC, agustinVon commented on src/features/filter/Filter.js
> +import { BRANDS, COLORS, FUEL_TYPES, CAR_DOORS, GEAR_SHIFT_TYPES } from '../../utils/constants';
No se pushearon estas constantes. Arma un file de constants dentro de una nueva carpeta que se llame mocks en utils

2023-09-06 14:18 UTC, agustinVon commented on src/features/filter/Filter.js
> +                display: 'flex',
La idea de los grids es que flex no es necesario. Osea usas Grid o Box con display flex. No los dos juntos.

2023-09-06 14:46 UTC, ChinoCoder commented on src/features/filter/Filter.js
> +import { BRANDS, COLORS, FUEL_TYPES, CAR_DOORS, GEAR_SHIFT_TYPES } from '../../utils/constants';
brands, colors, etc las subi en otro pr a develop hace unos dias. (BID-50)

2023-09-06 23:53 UTC, agustinVon approved these changes

2023-09-06 23:54 UTC, agustinVon requested changes

2023-09-06 23:54 UTC, agustinVon commented on src/features/filter/Filter.js
> +                    flex: 1,
Aca podes cambiar esto por un Box con flex en vez de grid

2023-09-06 23:55 UTC, agustinVon commented on src/features/filter/Filter.js
> +                    flex: 1,
<img width="485" alt="Screenshot 2023-09-06 at 20 55 04" src="https://github.com/Bid4Wheels/Bid4WheelsFront/assets/56046376/3df2eb1f-cf06-4668-bdd1-4b9aa12bcd29">
En esta parte la izquierda tiene que estar alineada

2023-09-07 12:51 UTC, agustinVon requested changes

2023-09-07 12:51 UTC, agustinVon commented on src/features/filter/Filter.js
> +            <Grid item xs={4}>
Sigue pasando el desalineado, el issue esta en estas lineas creo. Cambiate el grid que wrapea este por un box con flex y un gap

2023-09-07 21:39 UTC, agustinVon approved these changes

2023-09-07 21:42 UTC, merged