[BID-85] Cambio de contraseña: input de mail
Bid4Wheels/Bid4WheelsFront pull request #32
Opened 2023-09-11 17:25 UTC by bautistamasssanti

… to inputMail.js instead of validateIdentity.js

2023-09-11 22:38 UTC, agustinVon requested changes

2023-09-11 22:38 UTC, agustinVon commented on src/features/logIn/inputMail.js
> +                        onClick={() => nav('/validateIdentity')}
Podrias hacer que cuando se continua aca tambien guarde el email en el userSlice?

2023-09-14 12:47 UTC, agustinVon requested changes

2023-09-14 12:47 UTC, agustinVon commented on src/features/logIn/inputMail.js
> +        if (!emailValue || !/^\S+@\S+\.\S+$/.test(emailValue)) {
Ya tenemos un regex para mail en utils. Y si no tenemos deberia estar ahi

2023-09-14 12:47 UTC, agustinVon commented on src/features/logIn/inputMail.js
> +            setIsButtonDisabled(false);
Esta faltando el dispatch al slice. Fijate que Santi agrego una action para updetear el mail.

2023-09-14 18:33 UTC, bautistamasssanti commented on src/features/logIn/inputMail.js
> +            setIsButtonDisabled(false);
el dispatch esta en la linea 87 de inputMail

2023-09-14 20:29 UTC, agustinVon approved these changes

2023-09-14 20:29 UTC, merged