[BID-79] Modal de confirmacion e input de monto
Bid4Wheels/Bid4WheelsFront pull request #42
Opened 2023-09-15 18:58 UTC by ChinoCoder

UI Fixes del Widget se van a realizar sobre BID-78. Este PR es principalmente para el Modal

2023-09-18 14:22 UTC, agustinVon requested changes

2023-09-18 14:22 UTC, agustinVon commented on src/features/auction/Auction.js
> +                <Box
Podes sacar el widget este a un componente aparte?

2023-09-18 14:22 UTC, agustinVon commented on src/features/auction/Auction.js
> +                    <TextField
Este textfield pierde focus cuando escribis algo. Seguro que hay un tema con el useState. Cuando separes esto en un nuevo componente capaz se arregla.

2023-09-18 14:22 UTC, agustinVon commented on src/features/auction/Auction.js
> +                                width: '70%',
Esta box no es necesaria. Directamente poneselo al boton

2023-09-18 14:22 UTC, agustinVon commented on src/features/auction/Auction.js
> +                                    maxWidth: '100px',
Esta width hace que wrapee el texto dentro del boton. Agranda un poquito para q no lo haga

2023-09-18 20:57 UTC, ChinoCoder commented on src/features/auction/Auction.js
> +                                width: '70%',
la box esta la estaba usando para que aparezca el mensaje sobre el boton, xq cuando esta disabled no le aparece el tooltip que le agregue

2023-09-21 12:27 UTC, agustinVon approved these changes

2023-09-21 13:04 UTC, merged