[BID-110] Componente de visualización de tiempo restante
Bid4Wheels/Bid4WheelsFront pull request #75
Opened 2023-10-03 19:46 UTC by ChinoCoder

Como la información de la auction no tiene el horario de creación, el porcentaje de la barra muestra lo que le queda de las últimas 24 horas (si quedan 12 horas, la barra estará al 50%, si queda más de un día, estará al 100%)

2023-10-05 02:10 UTC, agustinVon requested changes

2023-10-05 02:10 UTC, agustinVon commented on src/features/commons/TimeBar.js
> +                    {`${hours}:${minutes}:${seconds}`}
Ya que estas con esto. Te pido si cambiamos de: "dd:hh:mm" a "d dias, h horas, mm:ss minutos"

2023-10-05 03:07 UTC, ChinoCoder commented on src/features/commons/TimeBar.js
> +                    {`${hours}:${minutes}:${seconds}`}
lo deje como dd d, hh hr, mm:ss mins porque con las palabras completas estiraba el componente, y con eso tambien las auction cards

2023-10-05 20:02 UTC, agustinVon commented
Los chicos del back estan por agregar la fecha de inicio de la subasta. Una vez este eso podes agregarlo en esta branch?

2023-10-12 04:34 UTC, agustinVon commented
<img width="1728" alt="Screenshot 2023-10-12 at 01 33 35" src="https://github.com/Bid4Wheels/Bid4WheelsFront/assets/56046376/7ae9ce02-0f1b-47c3-aa0a-761ce3faf679">
Deberia estar por la mitad la barra masomenos siendo que me fije esto el 12

2023-10-12 21:01 UTC, agustinVon approved these changes

2023-10-12 21:02 UTC, merged