[BID-141] Pagina de 404 Not found - Manejo de rutas no existentes
Bid4Wheels/Bid4WheelsFront pull request #80
Opened 2023-10-07 00:25 UTC by bautistamasssanti

2023-10-12 16:59 UTC, agustinVon commented
<img width="1728" alt="Screenshot 2023-10-12 at 13 57 20" src="https://github.com/Bid4Wheels/Bid4WheelsFront/assets/56046376/4176e3cb-1a73-4847-9199-ae2e6f8514aa">
No funciona para auctions

2023-10-12 16:59 UTC, agustinVon requested changes
Cambios requeridos

2023-10-12 20:51 UTC, bautistamasssanti commented
> <img alt="Screenshot 2023-10-12 at 13 57 20" width="1728" src="https://user-images.githubusercontent.com/56046376/274674280-4176e3cb-1a73-4847-9199-ae2e6f8514aa.png"> No funciona para auctions

fíjate que pusiste acution, puede ser que haya tomado eso como path del de confirmar una subasta, si pones /auction/ un numero aleatorio debería funcionar como en la captura que mando acá
![Captura de pantalla 2023-10-12 175043](https://github.com/Bid4Wheels/Bid4WheelsFront/assets/72039140/c9cfac69-1105-4ddd-a35f-7ca19f76bb11)

2023-10-16 23:05 UTC, agustinVon approved these changes

2023-10-17 01:43 UTC, merged